# 完整功能配置範例
# 啟用所有 topics，適用於完整的系統測試和開發

# 全部啟用
enable_status_pub: true
enable_mission_sub: true
enable_velocity_sub: true
enable_gps_pub: true
enable_attitude_pub: true
enable_battery_pub: true
enable_obstacle_pub: true
enable_waypoint_sub: true
enable_emergency_sub: true
